on:
  workflow_dispatch:
  push:
    branches:
      - '**'

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install Jupyter nbconvert
        run: |
          python -m pip install --upgrade pip
          pip install jupyter

      - name: Execute Jupyter Notebook
        run: |
          # Execute hello.ipynb
          jupyter nbconvert --execute hello.ipynb --to notebook --output hello.ipynb


      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
